// Bilingual fragrance-note catalog — the olfactory pyramid the admin picks from,
// and the seed source for the public.notes table (scripts/seed-notes.mjs).
// Keys are the note family; they must be members of FAMILIES in ./taxonomy.js.
// Extracted verbatim from AdminProduct.jsx, where it lived inline.

export const NOTES_CATALOG = {
  citrus: [
    { en: "Bergamot",              ar: "برغموت" },
    { en: "Bigarade",              ar: "بيجاراد / برتقال مر" },
    { en: "Bitter Orange",         ar: "برتقال مر" },
    { en: "Black Lemon",           ar: "لومي أسود" },
    { en: "Blood Orange",          ar: "برتقال دموي" },
    { en: "Buddha's Hand",         ar: "يد بوذا" },
    { en: "Calamansi",             ar: "كالامانسي" },
    { en: "Candied Lemon",         ar: "ليمون مُحلى" },
    { en: "Chen Pi",               ar: "قشر اليوسفي المجفف" },
    { en: "Chinotto",              ar: "كينوتو" },
    { en: "Citron",                ar: "أترج" },
    { en: "Citrus Japonica",       ar: "يوزو / كمكوات" },
    { en: "Citrus Water",          ar: "ماء الحمضيات" },
    { en: "Citruses",              ar: "حمضيات عامة" },
    { en: "Clementine",            ar: "كليمانتين" },
    { en: "Crystalfizz",           ar: "كريستال فيز" },
    { en: "Finger Lime",           ar: "ليمون الأصابع" },
    { en: "Grapefruit",            ar: "جريب فروت" },
    { en: "Grapefruit Leaf",       ar: "ورق الجريب فروت" },
    { en: "Grapefruit Peel",       ar: "قشر الجريب فروت" },
    { en: "Grapefruit Soda",       ar: "صودا الجريب فروت" },
    { en: "Green Tangerine",       ar: "يوسفي أخضر" },
    { en: "Hassaku",               ar: "هاساكو" },
    { en: "Hatkora Lemon",         ar: "ليمون هاتكورا" },
    { en: "Kabosu",                ar: "كابوسو" },
    { en: "Kaffir Lime",           ar: "ليمون كفير" },
    { en: "Kumquat",               ar: "كمكوات" },
    { en: "Lemon",                 ar: "ليمون" },
    { en: "Lemon Balm",            ar: "مليسة / بلسم الليمون" },
    { en: "Lemon Myrtle",          ar: "ميرتل الليمون" },
    { en: "Lemon Tree",            ar: "شجرة الليمون" },
    { en: "Lemon Verbena",         ar: "لويزة الليمون" },
    { en: "Lemon Zest",            ar: "بشر الليمون" },
    { en: "Lemongrass",            ar: "عشب الليمون" },
    { en: "Lime",                  ar: "ليمون حامض" },
    { en: "Limetta",               ar: "ليميتا" },
    { en: "Litsea Cubeba",         ar: "ليتسيا كوبيبا" },
    { en: "Mandarin Orange",       ar: "يوسفي" },
    { en: "Mandora",               ar: "ماندورا" },
    { en: "Methyl Pamplemousse",   ar: "ميثيل بامبل موس" },
    { en: "Murcott",               ar: "موركوت" },
    { en: "Neroli",                ar: "نيرولي" },
    { en: "Orange",                ar: "برتقال" },
    { en: "Palestinian Sweet Lime",ar: "ليمون حلو فلسطيني" },
    { en: "Perfume Lemon",         ar: "ليمون عطري" },
    { en: "Petitgrain",            ar: "بتيت جرين" },
    { en: "Pokan",                 ar: "بوكان" },
    { en: "Pomelo",                ar: "بوملي" },
    { en: "Quenepa",               ar: "كينيبا" },
    { en: "Rangpur",               ar: "ليمون رانجوبور" },
    { en: "Red Mandarin",          ar: "يوسفي أحمر" },
    { en: "Rind Bergamot",         ar: "قشر البرغموت" },
    { en: "Shiikuwasha",           ar: "شييكواشا" },
    { en: "Sudachi Citrus",        ar: "سوداتشي" },
    { en: "Tangelo",               ar: "تانجيلو" },
    { en: "Tangerine",             ar: "يوسفي" },
    { en: "Tangerine Zest",        ar: "بشر اليوسفي" },
    { en: "Yuzu",                  ar: "يوزو" },
  ],
  fruity: [
    { en: "Acai Berry", ar: "توت الآساي" },
    { en: "Acerola", ar: "أسيرولا" },
    { en: "Acorn", ar: "بلوط" },
    { en: "Akebia fruit", ar: "فاكهة الأكيبيا" },
    { en: "Almond", ar: "لوز" },
    { en: "Apple", ar: "تفاح" },
    { en: "Apple Juice", ar: "عصير التفاح" },
    { en: "Apple Pulp", ar: "لب التفاح" },
    { en: "Apple Sherbet", ar: "شربات التفاح" },
    { en: "Apricot", ar: "مشمش" },
    { en: "Arctic Bramble", ar: "توت العليق القطبي" },
    { en: "Argan", ar: "أركان" },
    { en: "Artichoke", ar: "خرشوف" },
    { en: "Ashberry", ar: "توت الرماد" },
    { en: "Banana", ar: "موز" },
    { en: "Barberry", ar: "البرباريس" },
    { en: "Bearberry", ar: "عنب الدب" },
    { en: "Beetroot", ar: "بنجر / شمندر" },
    { en: "Berries", ar: "توت بري" },
    { en: "Bitter melon", ar: "البطيخ المر" },
    { en: "Black Cherry", ar: "كرز أسود" },
    { en: "Black Currant", ar: "كشمش أسود" },
    { en: "Black Sapote", ar: "سبوتة سوداء" },
    { en: "Black Walnut", ar: "جوز أسود" },
    { en: "Blackberry", ar: "توت العليق الأسود" },
    { en: "Blackthorn", ar: "البرقوق البري" },
    { en: "Blueberry", ar: "توت أزرق" },
    { en: "Boysenberry", ar: "بويزنبيري" },
    { en: "Brazil Nut", ar: "جوز البرازيل" },
    { en: "Breadnut", ar: "جوز الخبز" },
    { en: "Buriti", ar: "بوريتي" },
    { en: "Burning Cherry", ar: "كرز محترق" },
    { en: "Cabernet Grape", ar: "عنب كابيرنيه" },
    { en: "Calafate", ar: "كالافات" },
    { en: "Candlenut", ar: "جوز الشمع" },
    { en: "Cantaloupe", ar: "كانتالوب / شمام" },
    { en: "Carambola", ar: "فاكهة النجمة / كارامبولا" },
    { en: "Carrot", ar: "جزر" },
    { en: "Cashew", ar: "كاجو" },
    { en: "Cassowary Fruit", ar: "فاكهة الكاسواري" },
    { en: "Cauliflower", ar: "قرنبيط" },
    { en: "Cepes", ar: "فطر البورسيني" },
    { en: "Chayote", ar: "شايوت" },
    { en: "Cherimoya", ar: "شيريمويا" },
    { en: "Cherry", ar: "كرز" },
    { en: "Cherry Jam", ar: "مربى الكرز" },
    { en: "Chestnut", ar: "كستناء" },
    { en: "Chia Seed", ar: "بذور الشيا" },
    { en: "Chickpeas", ar: "حمص" },
    { en: "Chinese Magnolia", ar: "ماغنوليا صينية" },
    { en: "Cider Apple", ar: "تفاح السدر" },
    { en: "Cloudberry", ar: "توت السحاب" },
    { en: "Coco De Mer", ar: "جوز الهند البحري" },
    { en: "Cocoa shell", ar: "قشرة الكاكاو" },
    { en: "Coconut", ar: "جوز الهند" },
    { en: "Coconut Water", ar: "ماء جوز الهند" },
    { en: "Cogumelo Porcino", ar: "فطر بورسيني" },
    { en: "Conifer", ar: "صنوبريات" },
    { en: "Corn", ar: "ذرة" },
    { en: "Corn Silk", ar: "حرير الذرة" },
    { en: "Count's Fruit", ar: "فاكهة الكونت" },
    { en: "Cranberry", ar: "توت بري أحمر" },
    { en: "Crimson Fruits", ar: "فواكه قرمذية" },
    { en: "Cucumber", ar: "خيار" },
    { en: "Cupuaçu", ar: "كوبواسو" },
    { en: "Currant Leaf and Bud", ar: "أوراق وبراعم الكشمش" },
    { en: "Cyperus Scariosus", ar: "السعد الهندي" },
    { en: "Daikon Radish", ar: "فجل ديكون" },
    { en: "Dark Plum Wu Mei", ar: "برقوق داكن (وو مي)" },
    { en: "Decalepis hamiltonii", ar: "ديكاليبس هاملتوني" },
    { en: "Dewberry", ar: "ندى التوت" },
    { en: "Dried Apple Crisp", ar: "رقائق التفاح المجفف" },
    { en: "Dried Apricot", ar: "مشمش مجفف" },
    { en: "Dried Fruits", ar: "فواكه مجففة" },
    { en: "Durian", ar: "دوريان" },
    { en: "Elderberry", ar: "توت البيلسان" },
    { en: "Feijoa Fruit", ar: "فيجوا" },
    { en: "Fig", ar: "تين" },
    { en: "Fig Leaf", ar: "ورق التين" },
    { en: "Fig Milk", ar: "حليب التين" },
    { en: "Filbertone", ar: "فيلبرتون" },
    { en: "Flowering Gourd", ar: "قرع مزهر" },
    { en: "Forest Fruits", ar: "فواكه الغابة" },
    { en: "Frosted Berries", ar: "توت مثلج" },
    { en: "Fruit Salad", ar: "سلطة فواكه" },
    { en: "Fruity Notes", ar: "نوتات فاكهية" },
    { en: "Fuji Apple", ar: "تفاح فوجي" },
    { en: "Gariguette Strawberry", ar: "فراولة غاريغيت" },
    { en: "Genipapo", ar: "جينيبابو" },
    { en: "Goji Berries", ar: "توت الغوجي" },
    { en: "Goldenberry", ar: "الحرنكش / التوت الذهبي" },
    { en: "Gooseberry", ar: "عنب الثعلب" },
    { en: "Grains", ar: "حبوب" },
    { en: "Grape Seed", ar: "بذور العنب" },
    { en: "Grapes", ar: "عنب" },
    { en: "Green Anjou Pears", ar: "كمثرى أنجو الخضراء" },
    { en: "Green Banana", ar: "موز أخضر" },
    { en: "Green Grape", ar: "عنب أخضر" },
    { en: "Green Pear", ar: "كمثرى خضراء" },
    { en: "Green Plum", ar: "برقوق أخضر" },
    { en: "Greengage", ar: "برقوق أخضر جرين جيج" },
    { en: "Ground Cherry", ar: "حرنكش الأرض" },
    { en: "Guarana", ar: "غوارانا" },
    { en: "Guava", ar: "جوافة" },
    { en: "Guava Nectar", ar: "رحيق الجوافة" },
    { en: "Hazelnut", ar: "بندق" },
    { en: "Hog Plum", ar: "برقوق الخنزير" },
    { en: "Honeydew Melon", ar: "شمام عسلي" },
    { en: "Isabella Grape", ar: "عنب إيزابيلا" },
    { en: "Jabuticaba", ar: "جابوتيكابا" },
    { en: "Jackfruit", ar: "جاك فروت" },
    { en: "Japanese Loquat", ar: "اسكدنيا يابانية" },
    { en: "Jobs Tears", ar: "دموع أيوب" },
    { en: "Kiwi", ar: "كيوي" },
    { en: "Kumbaru", ar: "كومبارو" },
    { en: "Lingonberry", ar: "لينجونبيري" },
    { en: "Litchi", ar: "ليتشي" },
    { en: "Loganberry", ar: "لوغانبيري" },
    { en: "Longan Berries", ar: "توت لونغان" },
    { en: "Lotus Seed", ar: "بذور اللوتس" },
    { en: "Lucuma", ar: "لوكوما" },
    { en: "Macadamia", ar: "مكاديميا" },
    { en: "Mahonia", ar: "ماهونيا" },
    { en: "Malt", ar: "شعير" },
    { en: "Mamey", ar: "مامي" },
    { en: "Mango", ar: "مانجو" },
    { en: "Mangosteen", ar: "مانغوستين" },
    { en: "Maninka", ar: "مانينكا" },
    { en: "Maqui Berry", ar: "توت الماكي" },
    { en: "Marian Plum", ar: "برقوق ماريان" },
    { en: "Medlar", ar: "زعرور" },
    { en: "Melon", ar: "شمام" },
    { en: "Millet", ar: "دخن" },
    { en: "Mirabelle", ar: "برقوق ميرابيل" },
    { en: "Miracle Berry", ar: "التوت المعجزة" },
    { en: "Moepel Accord", ar: "أكورد المويبيل" },
    { en: "Mulberry", ar: "توت" },
    { en: "Mung Bean", ar: "فاصوليا الماش" },
    { en: "Mushroom", ar: "فطر / عيش الغراب" },
    { en: "Nalca", ar: "نالكا" },
    { en: "Nashi Pear", ar: "كمثرى ناشي" },
    { en: "Nectarine", ar: "نكتارين" },
    { en: "Nutty Notes", ar: "نوتات مكسرات" },
    { en: "Okra Seeds", ar: "بذور البامية" },
    { en: "Olive", ar: "زيتون" },
    { en: "Papaya", ar: "بابايا" },
    { en: "Passionfruit", ar: "ماراكوجا / فاكهة العاطفة" },
    { en: "Pea", ar: "بازلاء" },
    { en: "Peach", ar: "خوخ (دراق)" },
    { en: "Peanut", ar: "فول سوداني" },
    { en: "Pear", ar: "كمثرى" },
    { en: "Pecan", ar: "بيكان" },
    { en: "Persimmon", ar: "كاكي" },
    { en: "Peruvian Pepper", ar: "فلفل بيروفي" },
    { en: "Pineapple", ar: "أناناس" },
    { en: "Pinot Noir Grapes", ar: "عنب بينو نوار" },
    { en: "Pistachio", ar: "فستق" },
    { en: "Pitahaya", ar: "فاكهة التنين" },
    { en: "Pitanga", ar: "بيتانغا" },
    { en: "Plantain", ar: "موز للطهي" },
    { en: "Plum", ar: "خوخ/برقوق" },
    { en: "Pomegranate", ar: "رمان" },
    { en: "Potato", ar: "بطاطس" },
    { en: "Prickly Pear", ar: "تين شوكي" },
    { en: "Pumpkin", ar: "قرع" },
    { en: "Purple Yam", ar: "يام أرجواني" },
    { en: "Quandong", ar: "كواندونغ" },
    { en: "Quince", ar: "سفرجل" },
    { en: "Rambutan", ar: "رامبوتان" },
    { en: "Raspberry", ar: "توت العليق الأحمر" },
    { en: "Red Apple", ar: "تفاح أحمر" },
    { en: "Red Berries", ar: "توت أحمر" },
    { en: "Red Currant", ar: "كشمش أحمر" },
    { en: "Red Fruits", ar: "فواكه حمراء" },
    { en: "Red Fruits Smoothie", ar: "عصير الفواكه الحمراء" },
    { en: "Red Mulberry", ar: "توت أحمر" },
    { en: "Rhubarb", ar: "راوند" },
    { en: "Roasted Nuts", ar: "مكسرات محمصة" },
    { en: "Rose Apple", ar: "تفاح الورد" },
    { en: "Rowanberry", ar: "توت الروان" },
    { en: "Salak", ar: "صالاك" },
    { en: "Santol", ar: "سانتول" },
    { en: "Sapodilla", ar: "سابوديلا" },
    { en: "Sarsaparilla", ar: "سرساباريلا" },
    { en: "Sea Buckthorn", ar: "نبق البحر" },
    { en: "Seriguela", ar: "سيريغويلا" },
    { en: "Serrano Pepper", ar: "فلفل سيرانو" },
    { en: "Shea Butter", ar: "زبدة الشيا" },
    { en: "Shea Nuts", ar: "مكسرات الشيا" },
    { en: "Silverberry", ar: "توت فضي" },
    { en: "Snowberry", ar: "توت الثلج" },
    { en: "Sour Cherry", ar: "كرز حامض" },
    { en: "Soursop", ar: "قشطة / جوانابانا" },
    { en: "Soybean", ar: "فول الصويا" },
    { en: "Squash", ar: "كوسة/قرع" },
    { en: "Star Apple", ar: "تفاح النجمة" },
    { en: "Strawberry", ar: "فراولة" },
    { en: "Strawberry Jam", ar: "مربى الفراولة" },
    { en: "SugarLoaf Pineapple", ar: "أناناس سو" },
    { en: "Garlic", ar: "ثوم" },
    { en: "Tamanu", ar: "تامانو" },
    { en: "Tapioca", ar: "تابيوكا" },
    { en: "Taro", ar: "قلقاس" },
    { en: "Tayberry", ar: "توت تاي" },
    { en: "Tomato", ar: "طماطم" },
    { en: "Tropical Fruits", ar: "فواكه استوائية" },
    { en: "Tropicalone", ar: "تروبيكالون" },
    { en: "Tucumã", ar: "توكوما" },
    { en: "Vegetal Notes", ar: "نوتات نباتية" },
    { en: "Walnut", ar: "جوز" },
    { en: "Walnut Milk", ar: "حليب الجوز" },
    { en: "Water Fruit", ar: "فاكهة مائية" },
    { en: "Watermelon", ar: "بطيخ أحمر" },
    { en: "Wattleseed", ar: "بذور الواتل" },
    { en: "White Currant", ar: "كشمش أبيض" },
    { en: "White Grape", ar: "عنب أبيض" },
    { en: "White Mulberry", ar: "توت أبيض" },
    { en: "Wild Strawberry", ar: "فراولة بر" },
    { en: "Williams Pear", ar: "كمثرى ويليامز" },
    { en: "Winterberry", ar: "توت الشتاء" },
    { en: "Wintermelon", ar: "بطيخ الشتاء" },
    { en: "Wolfberry", ar: "تُوت الذئب (غوجي)" },
    { en: "Yellow Cherry", ar: "كرز أصفر" },
    { en: "Yellow Fruits", ar: "فواكه صفراء" },
    { en: "Yuca Cassava", ar: "كاسافا" },
    { en: "Yumberry", ar: "يومبيري" },
    { en: "Zucchini", ar: "كوسة" },
  ],
  floral: [
    { en: "Abelia", ar: "أبيليا" },
    { en: "Acacia", ar: "أكاسيا / طلح" },
    { en: "Acerola Blossom", ar: "زهر الأسيرولا" },
    { en: "African Marigold", ar: "مخملية أفريقية" },
    { en: "Aglaia", ar: "أغلايا" },
    { en: "Alba Rose", ar: "الورد الأبيض" },
    { en: "Albizia", ar: "ألبيزيا" },
    { en: "Almond Blossom", ar: "زهر اللوز" },
    { en: "Alpinia", ar: "ألبينيا" },
    { en: "Alstroemeria", ar: "ألستروميريا" },
    { en: "Althaea", ar: "خبازة / ختمية" },
    { en: "Alumroot", ar: "ألومروت" },
    { en: "Alyssum", ar: "أليسار / أليسوم" },
    { en: "Amarillys", ar: "أماريليس" },
    { en: "Amazon Moonflower", ar: "زهرة القمر الأمازونية" },
    { en: "Amethyst Flower", ar: "زهرة الجمشت" },
    { en: "Anemone", ar: "شقائق النعمان" },
    { en: "Angel's Trumpet", ar: "بوق الملاك" },
    { en: "Apple Blossom", ar: "زهر التفاح" },
    { en: "Apricot Blossom", ar: "زهر المشمش" },
    { en: "Ashoka Flower", ar: "زهرة أشوكا" },
    { en: "Asian Clintonia", ar: "كلينتونيا آسيوية" },
    { en: "Astragalus", ar: "قتاد / أستراغالوس" },
    { en: "Azalea", ar: "أزاليا" },
    { en: "Azteca Lily", ar: "زنبق الأزتيك" },
    { en: "Baby’s Breath", ar: "نفس الطفل / الجبسوفيلا" },
    { en: "Banana Flower", ar: "زهرة الموز" },
    { en: "Banksia Australian", ar: "بانكسيا أسترالية" },
    { en: "Begonia", ar: "بيغونيا" },
    { en: "Belladona", ar: "ست الحسن / بلادونا" },
    { en: "Bellflower", ar: "زهرة الجرس" },
    { en: "Bergamot Blossom", ar: "زهر البرغموت" },
    { en: "Bird cherry", ar: "كرز الطيور" },
    { en: "Black Currant Blossom", ar: "زهر الكشمش الأسود" },
    { en: "Blackberry Blossom", ar: "زهر توت العليق الأسود" },
    { en: "Blue Lilies", ar: "زنابق زرقاء" },
    { en: "Blue Pea Flower", ar: "زهرة البازلاء الزرقاء" },
    { en: "Blue Poppy", ar: "خشخاش أزرق" },
    { en: "Bluebell", ar: "جريس أزرق" },
    { en: "Bottlebrush", ar: "فرشاة الزجاج" },
    { en: "Bougainvillea", ar: "جهنية" },
    { en: "Bouvardia", ar: "بوفارديا" },
    { en: "Bread Flower", ar: "زهرة الخبز" },
    { en: "Bromelia", ar: "بروميليا" },
    { en: "Buddleia", ar: "بودليا" },
    { en: "Butomus Umbellatus", ar: "بوتوموس مظلي" },
    { en: "Buttercup", ar: "حوذان" },
    { en: "Cacao Blossom", ar: "زهر الكاكاو" },
    { en: "Cactus Blossom", ar: "زهر الصبار" },
    { en: "Calendula", ar: "أقحوان / كاليندولا" },
    { en: "Calla Lily", ar: "زنبق الكالا" },
    { en: "Camellia", ar: "كاميليا" },
    { en: "Campion Flower", ar: "سيلينة" },
    { en: "Cananga", ar: "كانانغا" },
    { en: "Cannonball Flower", ar: "زهرة شجرة المدفع" },
    { en: "Carambola Blossom", ar: "زهر الكارامبولا" },
    { en: "Cardamom Flower", ar: "زهرة الهيل" },
    { en: "Carnation", ar: "قرنفل" },
    { en: "Cashew Flower", ar: "زهرة الكاجو" },
    { en: "Celosia", ar: "سيلوسيا" },
    { en: "Chai Hu", ar: "تشاي هو" },
    { en: "Chamomile", ar: "بابونج" },
    { en: "Champaca", ar: "شامباكا" },
    { en: "Cherry Blossom", ar: "زهر الكرز" },
    { en: "Chimonanthus", ar: "شيمونانثوس" },
    { en: "China Rose", ar: "الورد الصيني" },
    { en: "Chinotto blossom", ar: "زهر الكينوتو" },
    { en: "Chocolate Flower", ar: "زهرة الشوكولاتة" },
    { en: "Christmas Tree", ar: "شجرة الصنوبر" },
    { en: "Chrysanthemum", ar: "أقحوان" },
    { en: "Cistus Incanus", ar: "قستوس رمادي" },
    { en: "Clematis", ar: "ياسمين بري / كليماتيس" },
    { en: "Clover", ar: "برسيم" },
    { en: "Coconut Blossom", ar: "زهر جوز الهند" },
    { en: "Coffee Blossom", ar: "زهر القهوة" },
    { en: "Cornflower", ar: "زهرة الذرة / العنبر" },
    { en: "Cosmos Flower", ar: "زهرة الكوزموس" },
    { en: "Costus", ar: "قسط" },
    { en: "Cotton Flower", ar: "زهرة القطن" },
    { en: "Creamy Flowers", ar: "زهور كريمية" },
    { en: "Crinum Lily", ar: "زنبق الكرينوم" },
    { en: "Cucumber Flower", ar: "زهرة الخيار" },
    { en: "Cyclamen", ar: "بخور مريم / سيكلامين" },
    { en: "Dahlia", ar: "داليا" },
    { en: "Daisy", ar: "أقحوان بري / ديزي" },
    { en: "Dandelion", ar: "هندباء البرية" },
    { en: "Daphne", ar: "دافني" },
    { en: "Daylily", ar: "زنبق النهار" },
    { en: "Deadnettle", ar: "لاميون" },
    { en: "Delonix", ar: "ديلونيكس" },
    { en: "Desert Rose", ar: "وردة الصحراء" },
    { en: "Dianthus", ar: "قرنفل" },
    { en: "Diviniris", ar: "ديفينيريس" },
    { en: "Dogwood Blossom", ar: "زهر شجرة القرانيا" },
    { en: "Dove Tree", ar: "شجرة الحمامة" },
    { en: "Dried Rose", ar: "ورد مجفف" },
    { en: "Dyer's Greenweed", ar: "وزال الصباغين" },
    { en: "Edelweiss", ar: "إديلوايس" },
    { en: "Eglantine Rose", ar: "الورد البري" },
    { en: "Elderflower", ar: "زهر البيلسان" },
    { en: "Encian", ar: "جنطيانا" },
    { en: "Erigeron", ar: "أريغارون" },
    { en: "Euphorbia", ar: "فربيون" },
    { en: "Eustoma", ar: "يوستوما" },
    { en: "Evergreen", ar: "دائم الخضرة" },
    { en: "Field Scabious", ar: "جرب الحقول" },
    { en: "Fig Blossom", ar: "زهر التين" },
    { en: "Fire Lily", ar: "زنبق النار" },
    { en: "Flamingo Flower", ar: "زهرة الفلامنغو / أنثوريوم" },
    { en: "Flax", ar: "كتان" },
    { en: "Floral Notes", ar: "نوتات زهرية" },
    { en: "Forget Me Not", ar: "لا تنساني" },
    { en: "Fragonia", ar: "فراغونيا" },
    { en: "Freesia", ar: "فريزيا" },
    { en: "French Marigold", ar: "قطيفة فرنسية" },
    { en: "Fringed Pink", ar: "قرنفل مهدب" },
    { en: "Fuchsia", ar: "فوشيا" },
    { en: "Geranium", ar: "جيرانيوم" },
    { en: "Gerbera", ar: "جربارة" },
    { en: "Gladiolus", ar: "دلبوث" },
    { en: "Goldenrod", ar: "عصا الذهب" },
    { en: "Gorse", ar: "جولق" },
    { en: "Grapeflower", ar: "زهر العنب" },
    { en: "Great Burnet", ar: "بوقيصا كبرى" },
    { en: "Green Nard", ar: "ناردين أخضر" },
    { en: "Green Tea Flower", ar: "زهرة الشاي الأخضر" },
    { en: "Grevillea", ar: "غريفيليا" },
    { en: "Guava Blossom", ar: "زهر الجوافة" },
    { en: "Guayacan", ar: "غواياكان" },
    { en: "Gustavia Flower", ar: "زهرة غوستافيا" },
    { en: "Hawthorn", ar: "زعرور" },
    { en: "Hazel Blossom", ar: "زهر البندق" },
    { en: "Heather", ar: "خلنج" },
    { en: "Heliotrope", ar: "رقيب الشمس / هليوتروب" },
    { en: "Hellabore Flower", ar: "زهرة الخربق" },
    { en: "Hemlock", ar: "شوكران" },
    { en: "Hibiscus", ar: "كركديه" },
    { en: "Hoary Stock", ar: "منثور رمادي" },
    { en: "Holly Flower", ar: "زهرة البهشية" },
    { en: "Hollyhock", ar: "خطمية" },
    { en: "Honeybush", ar: "شجيرة العسل" },
    { en: "Honeydew Blossom", ar: "زهر الشمام العسلي" },
    { en: "Hortensia", ar: "كوبية / هورتنسيا" },
    { en: "Hoya Carnosa", ar: "هويا كارنوسا" },
    { en: "Hyacinth", ar: "ياقوتية / هياسينث" },
    { en: "Hyssop", ar: "زوفا" },
    { en: "Impatiens", ar: "بلسم / إمباتينز" },
    { en: "Inula", ar: "عينات / إينولا" },
    { en: "Iris", ar: "سوسن" },
    { en: "Iris Butter", ar: "زبدة السوسن" },
    { en: "Iris Pallida", ar: "السوسن الشاحب" },
    { en: "Jacaranda", ar: "جاكراندا" },
    { en: "Jade Flower", ar: "زهرة اليشم" },
    { en: "Jarana Flower", ar: "زهرة جارانا" },
    { en: "Jasmine Orchid", ar: "أوركيد الياسمين" },
    { en: "Jujube Blossom", ar: "زهر العناب" },
    { en: "Kadam", ar: "كادام" },
    { en: "Kangaroo Paw", ar: "مخلب الكنغر" },
    { en: "Kanuka", ar: "كانوكا" },
    { en: "Kanzan Cherry", ar: "كرز كانزان" },
    { en: "Karmaflor", ar: "كارمافلور" },
    { en: "Kiwi blossom", ar: "زهر الكيوي" },
    { en: "Kudzu", ar: "كودزو" },
    { en: "Laburnum", ar: "شجرة المطر الذهبي" },
    { en: "Lady of the Night", ar: "سيدة الليل" },
    { en: "Lady Slipper Orchid", ar: "أوركيد خف السيدة" },
    { en: "Lamduan Flower", ar: "زهرة اللامدوان" },
    { en: "Lamprocapnos", ar: "قلب ينزف" },
    { en: "Lantana", ar: "لانتانا" },
    { en: "Larkspur", ar: "عائق" },
    { en: "Laurel Blossom", ar: "زهر الغار" },
    { en: "Lavender", ar: "خزامى / لافندر" },
    { en: "Leatherwood", ar: "خشب جلدي" },
    { en: "Ledum", ar: "ليدوم" },
    { en: "Liatrix", ar: "لياتريس" },
    { en: "Licorice Flower", ar: "زهرة عرق السوس" },
    { en: "Lilac", ar: "ليلك" },
    { en: "Lily-of-the-Valley", ar: "زنبق الوادي" },
    { en: "Lime Blossom", ar: "زهر الليمون الحامض" },
    { en: "Litchi Blossom", ar: "زهر الليتشي" },
    { en: "Longoza", ar: "لونغوزا" },
    { en: "Lotus", ar: "لوتس" },
    { en: "Lupin", ar: "ترمس" },
    { en: "Lydia Broom", ar: "وزال ليديا" },
    { en: "Lysylang", ar: "ليسيلانغ" },
    { en: "Macadamia Flower", ar: "زهرة المكاديميا" },
    { en: "Madonna Lily", ar: "زنبق مادونا" },
    { en: "Magnolia", ar: "ماغنوليا" },
    { en: "Magnolia Brooklynensis", ar: "ماغنوليا بروكلين" },
    { en: "Magnolia Leaf", ar: "ورق الماغنوليا" },
    { en: "Mahonial", ar: "ماهونيال" },
    { en: "Malva", ar: "خبيزة" },
    { en: "Mango Blossom", ar: "زهر المانجو" },
    { en: "Mariposa Lily", ar: "زنبق ماريبوسا" },
    { en: "Mayflower", ar: "زهرة مايو" },
    { en: "Meadowsweet", ar: "حلوة المروج" },
    { en: "Melilotus", ar: "حندقوق" },
    { en: "Melissa Flower", ar: "زهرة المليسة" },
    { en: "Michelia", ar: "ميشيليا" },
    { en: "Michelia leaf", ar: "ورق الميشيليا" },
    { en: "Mignonette", ar: "مينيونيت" },
    { en: "Milkweeds", ar: "صقلاب" },
    { en: "Mimosa", ar: "ميموزا" },
    { en: "Mimusops Elengi", ar: "بيكول / ميموزوبس" },
    { en: "Mirabilis", ar: "شب الليل" },
    { en: "Monarda", ar: "موناردا" },
    { en: "Monoi Oil", ar: "زيت المونوي" },
    { en: "Moringa Blossom", ar: "زهر المورينجا" },
    { en: "Morning Glory", ar: "مجد الصباح" },
    { en: "Moss Flox", ar: "فلوكس الطحلب" },
    { en: "Myrtle", ar: "آس / مرسين" },
    { en: "Narcissus", ar: "نرجس" },
    { en: "Nard", ar: "ناردين" },
    { en: "Nasturtium", ar: "أبو خنجر" },
    { en: "Nectarine Blossom", ar: "زهر النكتارين" },
    { en: "Nerium Oleander", ar: "دفلى" },
    { en: "Nigella", ar: "حبة البركة" },
    { en: "Night Blooming Jasmine", ar: "ياسمين ليلي" },
    { en: "Nom Maew", ar: "نوم مايو" },
    { en: "Olive flower", ar: "زهر الزيتون" },
    { en: "Opium", ar: "أفيون" },
    { en: "Orange Cassia", ar: "كاسيا البرتقال" },
    { en: "Orange Flower Water", ar: "ماء زهر البرتقال" },
    { en: "Orange Jasmine", ar: "ياسمين البرتقال" },
    { en: "Orchard Blossom", ar: "زهر البساتين" },
    { en: "Orchid", ar: "أوركيد" },
    { en: "Orchid Black Diamond", ar: "أوركيد الماس الأسود" },
    { en: "Orchid Cactus", ar: "أوركيد الصبار" },
    { en: "Orchid Pink Leopard", ar: "أوركيد النمر الوردي" },
    { en: "Ornithogalum", ar: "نجمة بيت لحم" },
    { en: "Orris Root", ar: "جذر السوسن" },
    { en: "Osmanthus", ar: "أوسمانثوس" },
    { en: "Osmanthus milk", ar: "حليب الأوسمانثوس" },
    { en: "Pansy", ar: "زهرة الثالوث" },
    { en: "Papaya Blossom", ar: "زهر البابايا" },
    { en: "Paramela", ar: "باراميلا" },
    { en: "Passion Flower", ar: "زهرة الآلام" },
    { en: "Pataqueira", ar: "باتاكيرا" },
    { en: "Peach Blossom", ar: "زهر الخوخ" },
    { en: "Pear Blossom", ar: "زهر الكمثرى" },
    { en: "Pelargonium", ar: "بيلارغونيوم" },
    { en: "Peony", ar: "عود الصليب / بيوني" },
    { en: "Periwinkle", ar: "ونيكة" },
    { en: "Petalia", ar: "بيتاليا" },
    { en: "Petunia", ar: "بيتونيا" },
    { en: "Phlox", ar: "فلوكس" },
    { en: "Pikul Flower", ar: "زهرة بيكول" },
    { en: "Pineapple Blossom", ar: "زهر الأناناس" },
    { en: "Pink Flamingo Heliconia", ar: "هليكونيا الفلامنغو الوردي" },
    { en: "Pink Lily", ar: "زنبق وردي" },
    { en: "Pinwheel Flower", ar: "زهرة دولاب الهواء" },
    { en: "Pitahaya Flower", ar: "زهرة فاكهة التنين" },
    { en: "Pittosporum", ar: "بيتوسبوروم" },
    { en: "Plum Blossom", ar: "زهر البرقوق" },
    { en: "Plumeria", ar: "بلوميريا / ياسمين هندي" },
    { en: "Poinsettia", ar: "بنت القنصل" },
    { en: "Pomegranate Blossom", ar: "زهر الرمان" },
    { en: "Poppy", ar: "خشخاش" },
    { en: "Portlandia", ar: "بورتلانديا" },
    { en: "Primrose", ar: "زهرة الربيع" },
    { en: "Princess Tree", ar: "شجرة الأميرة" },
    { en: "Privet", ar: "شبة" },
    { en: "Protea", ar: "بروتيا" },
    { en: "Prunella", ar: "برونيلا" },
    { en: "Purple Coneflower", ar: "القنفذية الأرجوانية" },
    { en: "Queen of the Night", ar: "ملكة الليل" },
    { en: "Rangoon Creeper", ar: "الياسمين الأحمر" },
    { en: "Raspberry Blossom", ar: "زهر توت العليق" },
    { en: "Redwood Flower", ar: "زهرة الخشب الأحمر" },
    { en: "Reseda", ar: "خزامى صفراء" },
    { en: "Rhododendron", ar: "ردندرة" },
    { en: "Rosa Alba", ar: "الورد الأبيض" },
    { en: "Rosa Rubiginosa", ar: "الورد الياقوتي" },
    { en: "Rose", ar: "ورد" },
    { en: "Rose Hip", ar: "ثمر الورد" },
    { en: "Rose Japanese", ar: "الورد الياباني" },
    { en: "Rose Mallow", ar: "ختمية وردية" },
    { en: "Rosebay Willowherb", ar: "سنفية ضيقة الأوراق" },
    { en: "Rosebud", ar: "برعم الورد" },
    { en: "Roselle", ar: "كركديه" },
    { en: "Rosyfolia", ar: "روزيفوليا" },
    { en: "Safflower", ar: "عصفر" },
    { en: "Sainfoins", ar: "بيقية" },
    { en: "Sand Lily", ar: "زنبق الرمل" },
    { en: "Sandalwood Flower", ar: "زهرة خشب الصندل" },
    { en: "Santolina", ar: "سانتولينا" },
    { en: "Saucer Magnolia", ar: "ماغنوليا الكوب" },
    { en: "Sea Daffodil", ar: "نرجس البحر" },
    { en: "Siberian Rhododendron", ar: "ردندرة سيبيرية" },
    { en: "Silk Tree Blossom", ar: "زهر شجرة الحرير" },
    { en: "Silverthorn Flower", ar: "زهرة الشوك الفضي" },
    { en: "Skeleton Flower", ar: "زهرة الهيكل" },
    { en: "Smoketree", ar: "شجرة الدخان" },
    { en: "Snakeroot", ar: "جذر الأفعى" },
    { en: "Snow Lotus", ar: "لوتس الثلج" },
    { en: "Snowdrops", ar: "نقطة الثلج" },
    { en: "Solomon's Seal", ar: "ختم سليمان" },
    { en: "Sophora Toromiro", ar: "سوفورا تورومير" },
    { en: "Sour Cherry Blossom", ar: "زهر الكرز الحامض" },
    { en: "Spanish Broom", ar: "غريز إسباني" },
    { en: "Spiraea", ar: "سبيريا" },
    { en: "St. John's Wort", ar: "نبتة القديس يوحنا" },
    { en: "Star Magnolia", ar: "مانيوليا النجمة" },
    { en: "Starflower", ar: "زهرة النجمة" },
    { en: "Strawberry Flower", ar: "زهرة الفرا" },
    { en: "Strelitzia", ar: "نجمة الجنة" },
    { en: "Strobilanthes Callosa", ar: "ستروبيلانثيس" },
    { en: "Sunflower", ar: "دوار الشمس" },
    { en: "Sweet Pea", ar: "بسلة حلوة" },
    { en: "Taif Rose", ar: "وردة الطائف" },
    { en: "Tamarisk", ar: "طرفاء" },
    { en: "Tobacco Blossom", ar: "زهرة التبغ" },
    { en: "Transparent Flowers", ar: "زهور شفافة" },
    { en: "Trillium", ar: "ثلاثية الأوراق" },
    { en: "Tulip", ar: "خزامى / توليب" },
    { en: "Tussilago farfara", ar: "مرعى السعال" },
    { en: "Vanilla Bahiana", ar: "فانيليا باهيانية" },
    { en: "Viburnum", ar: "فيبورنوم" },
    { en: "Violet", ar: "بنفسج" },
    { en: "Violet Wood", ar: "خشب البنفسج" },
    { en: "Violet Sorrel", ar: "حميض البنفسج" },
    { en: "Wallflower", ar: "زهرة الجدار" },
    { en: "Waratah", ar: "وراتاه" },
    { en: "Water Flowers", ar: "زهور مائية" },
    { en: "Water Hyacinth", ar: "رسن مائي" },
    { en: "Water Lily", ar: "زنبق الماء" },
    { en: "Weeping Cherry Blossom", ar: "زهر الكرز الباكي" },
    { en: "White Champaca", ar: "شامباكا بيضاء" },
    { en: "White Dahlia", ar: "داليا بيضاء" },
    { en: "White Ginger Lily", ar: "زنبق الزنجبيل الأبيض" },
    { en: "White Lace Flower", ar: "زهرة الدانتيل البيضاء" },
    { en: "White Tea Blossom", ar: "زهرة الشاي الأبيض" },
    { en: "Wildflowers", ar: "زهور برية" },
    { en: "Winter Daphne", ar: "دافني الشتاء" },
    { en: "Wisteria", ar: "ويستيريا" },
    { en: "Wrightia", ar: "رايتيا" },
    { en: "Yellow Bells", ar: "أجراس صفراء" },
    { en: "Yellow Flowers", ar: "زهور صفراء" },
    { en: "Ylang-Ylang", ar: "يلانغ يلانغ" },
    { en: "Yunnan Osmanthus", ar: "أوزمانثوس يونان" },
    { en: "Yuzu Flower", ar: "زهرة اليوزو" },
    { en: "Zinnia", ar: "زينيا" },
    // White Flowers
    { en: "Arum Lily", ar: "زنبق الأروم" },
    { en: "Belanis", ar: "بيلانيس" },
    { en: "Black Locust", ar: "السنط الأسود" },
    { en: "Boronia", ar: "بورونيا" },
    { en: "Carissa", ar: "كاريسا" },
    { en: "Datura", ar: "داتورا" },
    { en: "Frangipani", ar: "فرنجيباني" },
    { en: "Gardenia", ar: "غاردينيا" },
    { en: "Grapefruit Blossom", ar: "زهر الجريب فروت" },
    { en: "Honeysuckle", ar: "صريمة الجدي" },
    { en: "Jasmine", ar: "ياسمين" },
    { en: "Karo-Karounde", ar: "كارو كاروندي" },
    { en: "Lemon Blossom", ar: "زهر الليمون" },
    { en: "Lily", ar: "زنبق" },
    { en: "Mandarin Orange Blossom", ar: "زهر اليوسفي" },
    { en: "Melati", ar: "ياسمين إندونيسي" },
    { en: "Mock Orange", ar: "الياسمين الكاذب" },
    { en: "Moon Flower", ar: "زهرة القمر" },
    { en: "Night Blooming Cereus", ar: "صبار ملكة الليل" },
    { en: "Orange Blossom", ar: "زهر البرتقال" },
    { en: "Stephanotis", ar: "ياسمين مدغشقر" },
    { en: "Syringa", ar: "ليلك كاذب" },
    { en: "Tangerine Blossom", ar: "زهر اليوسفي" },
    { en: "Tiare Flower", ar: "زهرة التياري" },
    { en: "Tuberose", ar: "مسك الروم" },
    { en: "White Flowers", ar: "زهور بيضاء" },
    { en: "White Tobacco", ar: "التبغ الأبيض" },
  ],
  spicy: [
    { en: "Allspice", ar: "بهار حلو" },
    { en: "Anise", ar: "يانسون" },
    { en: "Asafoetida", ar: "حلتيت" },
    { en: "Baking Spices", ar: "بهارات الخبيز" },
    { en: "Bay Leaf", ar: "ورق الغار" },
    { en: "Bengal Pepper", ar: "فلفل البنغال" },
    { en: "Biryani", ar: "بهارات البرياني" },
    { en: "Black Sesame", ar: "سمسم أسود" },
    { en: "Cacao Pod", ar: "قرن الكاكاو" },
    { en: "Caraway", ar: "كروية" },
    { en: "Cardamom", ar: "هيل (حبهان)" },
    { en: "Carolina Reaper", ar: "كارولينا ريبر" },
    { en: "Carum", ar: "كروية / كاروم" },
    { en: "Cassia", ar: "قرفة صينية" },
    { en: "Chutney", ar: "صلصة التشاتني" },
    { en: "Cinnamon", ar: "قرفة" },
    { en: "Cinnamon Leaf", ar: "ورق القرفة" },
    { en: "Clove Leaf", ar: "ورق القرنفل" },
    { en: "Cloves", ar: "قرنفل (توابل)" },
    { en: "Coffee", ar: "قهوة" },
    { en: "Coffee CO2", ar: "مستخلص القهوة" },
    { en: "Coffee Tincture", ar: "صبغة القهوة" },
    { en: "Coriander", ar: "كزبرة" },
    { en: "Cubeb", ar: "كبابة صينية" },
    { en: "Cumin", ar: "كمون" },
    { en: "Curcuma", ar: "كركم" },
    { en: "Curry", ar: "كاري" },
    { en: "Curry Tree", ar: "شجرة الكاري" },
    { en: "Dill", ar: "شبت" },
    { en: "Fennel", ar: "شمر" },
    { en: "Fenugreek", ar: "حلبة" },
    { en: "Galanga", ar: "خولنجان" },
    { en: "Ghost Pepper", ar: "فلفل شبح" },
    { en: "Ginger", ar: "زنجبيل" },
    { en: "Green Coffee", ar: "قهوة خضراء" },
    { en: "Guinea Pepper", ar: "فلفل غينيا" },
    { en: "Indian Spices", ar: "توابل هندية" },
    { en: "Japanese Pepper", ar: "فلفل ياباني" },
    { en: "Kaempferia Galanga", ar: "خولنجان طبي" },
    { en: "Kopi Luwak", ar: "قهوة كوبي لواك" },
    { en: "Licorice", ar: "عرق سوس" },
    { en: "Mace", ar: "قشرة جوزة الطيب" },
    { en: "Mustard Seed", ar: "بذور الخردل" },
    { en: "Nutmeg", ar: "جوزة الطيب" },
    { en: "Oily Notes", ar: "نوتات زيتية" },
    { en: "Oriental Notes", ar: "نوتات شرقية" },
    { en: "Pepper", ar: "فلفل" },
    { en: "Peppertree", ar: "شجرة الفلفل" },
    { en: "Pimento", ar: "فلفل حلو" },
    { en: "Pimento Leaf", ar: "ورق الفلفل الحلو" },
    { en: "Pimento Seeds", ar: "بذور الفلفل الحلو" },
    { en: "Pink Pepper", ar: "فلفل وردي" },
    { en: "Priprioca", ar: "بريبريوكا" },
    { en: "Saffron", ar: "زعفران" },
    { en: "Safraleine", ar: "سافرالين" },
    { en: "Sesame", ar: "سمسم" },
    { en: "Siam Cardamom", ar: "هيل سيامي" },
    { en: "Sichuan Pepper", ar: "فلفل سيشوان" },
    { en: "Spicy Notes", ar: "نوتات حارة / توابلية" },
    { en: "Spiked Pepper", ar: "فلفل مدبب" },
    { en: "Star Anise", ar: "يانسون نجمي" },
    { en: "Sumac", ar: "سماق" },
    { en: "Tamarind", ar: "تمر هندي" },
    { en: "Timur", ar: "تيمور" },
    { en: "Tonka Bean", ar: "حبوب التونكا" },
    { en: "Toscanol", ar: "توسكانول" },
    { en: "Ultravanil", ar: "ألترافانيل" },
    { en: "Vanilla", ar: "فانيليا" },
    { en: "Wan Sao Lhong", ar: "وان ساو لونغ" },
    { en: "Wasabi", ar: "واسابي" },
    { en: "Water Pepper", ar: "فلفل الماء" },
    { en: "West Indian Bay", ar: "ورق غار هندي" },
  ],};
